# This is a basic workflow to help you get started with Actions

name: UnitTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the setup branch
  push:
    branches: [ setup ]
  pull_request:
    branches: [ setup ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout branch
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      # Step 2.2: run MSBuild
      - name: Run MSBuild
        working-directory: $
        run: 'dir'
        #run: msbuild .\FTP.sln
     # Step 3.1: locate vstest.console.exe and add to PATH
      - name: Setup VSTest path
        uses: darenm/Setup-VSTest@v1
      
      - name: Run VSTest
        id: run_vstest
        working-directory: $\x64\Debug\
        run: vstest.console.exe /Platform:x64 .\UnitTest1.dll

     
