# This is a basic workflow to help you get started with Actions

name: UnitTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the setup branch
  push:
    branches: [ setup ]
  pull_request:
    branches: [ setup ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout branch
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /testcontainer:"D:\a\testVS2019UnitTestsAndActions\testVS2019UnitTestsAndActions\FTP\Debug\UnitTest1.dll"'
